"""rich text posts

Revision ID: 0a549826008f
Revises: 310ab6dec8e7
Create Date: 2016-08-26 20:32:02.409416

"""

# revision identifiers, used by Alembic.
revision = '0a549826008f'
down_revision = '310ab6dec8e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
