"""account confirmation

Revision ID: 0e32f3b5a3a6
Revises: f251e13bb9a5
Create Date: 2016-08-25 06:01:32.488077

"""

# revision identifiers, used by Alembic.
revision = '0e32f3b5a3a6'
down_revision = 'f251e13bb9a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
