"""chrome browser

Revision ID: 329a35dc3698
Revises: b0a35e1fc164
Create Date: 2016-09-16 22:20:50.711178

"""

# revision identifiers, used by Alembic.
revision = '329a35dc3698'
down_revision = 'b0a35e1fc164'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chrome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=5), nullable=True),
    sa.Column('arch', sa.String(length=6), nullable=True),
    sa.Column('channel', sa.String(length=6), nullable=True),
    sa.Column('version', sa.String(length=15), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chrome'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chrome')
    ### end Alembic commands ###
