"""post favorites

Revision ID: 64f717aa0b00
Revises: e376d33799ee
Create Date: 2016-09-08 23:55:08.337781

"""

# revision identifiers, used by Alembic.
revision = '64f717aa0b00'
down_revision = 'e376d33799ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_relationship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_favorite_relationship_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_relationship_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('pk_favorite_relationship'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_relationship')
    ### end Alembic commands ###
