"""caching of avatar hashes

Revision ID: 96674dc6f6b2
Revises: 121fe26b563f
Create Date: 2016-08-26 02:28:32.340484

"""

# revision identifiers, used by Alembic.
revision = '96674dc6f6b2'
down_revision = '121fe26b563f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
