"""article views

Revision ID: cdfa357a77a6
Revises: 7e4464b2c261
Create Date: 2016-09-04 05:46:46.326564

"""

# revision identifiers, used by Alembic.
revision = 'cdfa357a77a6'
down_revision = '7e4464b2c261'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_view', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('num_of_view')

    ### end Alembic commands ###
