"""user and blog views

Revision ID: e376d33799ee
Revises: cdfa357a77a6
Create Date: 2016-09-05 05:46:22.673310

"""

# revision identifiers, used by Alembic.
revision = 'e376d33799ee'
down_revision = 'cdfa357a77a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_addr', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('page', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_view'))
    )
    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_view', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.drop_column('num_of_view')

    op.drop_table('blog_view')
    ### end Alembic commands ###
